//! Seeded query benchmark: stock Postgres vs TimescaleDB columnstore cold tier.
//!
//! Seeds identical deterministic synthetic chain data (skewed address /
//! selector distributions, unique random hashes) into a stock Postgres and
//! a TimescaleDB server through the production write path, compresses all
//! chunks behind the hot window on the Timescale side, then measures the
//! serving query shapes on both.
//!
//! Run with:
//!   docker compose -f docker/local/docker-compose.yml up -d postgres timescaledb
//!   BENCH_BLOCKS=250000 cargo test --release --test timescale_bench -- --ignored --nocapture
//!
//! Env knobs:
//!   BENCH_BLOCKS          total blocks to seed (default 100,000)
//!   BENCH_TXS_PER_BLOCK   txs per block        (default 8)
//!   BENCH_LOGS_PER_BLOCK  logs per block       (default 16)
//!   STOCK_DATABASE_URL    default postgresql://tidx:tidx@localhost:5433/tidx
//!   TIMESCALE_DATABASE_URL default postgresql://tidx:tidx@localhost:5434/tidx

use chrono::{DateTime, TimeZone, Utc};
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};
use std::time::Instant;
use tidx::config::TimescaleConfig;
use tidx::db::{Pool, create_pool, run_migrations};
use tidx::query::apply_event_signature_ctes_postgres;
use tidx::sync::{timescale, writer};
use tidx::types::{BlockRow, LogRow, ReceiptRow, SyncState, TxRow};
use tokio_postgres::types::ToSql;

const CHAIN_ID: u64 = 42431;
const SEED: u64 = 42;
const BENCH_DB: &str = "tidx_bench";

fn env_u64(name: &str, default: u64) -> u64 {
    std::env::var(name)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(default)
}

struct Shape {
    blocks: i64,
    txs_per_block: i64,
    logs_per_block: i64,
    chunk_blocks: i64,
}

impl Shape {
    fn from_env() -> Self {
        let blocks = env_u64("BENCH_BLOCKS", 100_000) as i64;
        Self {
            blocks,
            txs_per_block: env_u64("BENCH_TXS_PER_BLOCK", 8) as i64,
            logs_per_block: env_u64("BENCH_LOGS_PER_BLOCK", 16) as i64,
            chunk_blocks: (blocks / 10).max(1),
        }
    }

    /// First hot block: everything below is cold on the Timescale side.
    fn hot_floor(&self) -> i64 {
        self.blocks - self.chunk_blocks
    }
}

fn ts(num: i64) -> DateTime<Utc> {
    Utc.timestamp_opt(1_760_000_000 + num, 0).unwrap()
}

fn bytes<const N: usize>(rng: &mut StdRng) -> Vec<u8> {
    let mut b = [0u8; N];
    rng.fill(&mut b[..]);
    b.to_vec()
}

/// Skewed pick: r^3 over `n` — a small head gets most of the traffic.
fn skewed(rng: &mut StdRng, n: u64) -> u64 {
    let r: f64 = rng.random();
    ((r * r * r) * n as f64) as u64
}

/// Deterministic 20-byte address from a pool of `n`, skewed.
fn addr(rng: &mut StdRng, tag: u8, n: u64) -> Vec<u8> {
    let idx = skewed(rng, n);
    let mut b = vec![0u8; 20];
    b[0] = tag;
    b[4..12].copy_from_slice(&idx.to_be_bytes());
    b
}

fn topic_from_addr(a: &[u8]) -> Vec<u8> {
    let mut t = vec![0u8; 32];
    t[12..32].copy_from_slice(a);
    t
}

/// keccak256("Transfer(address,address,uint256)") — the real topic0, so
/// event-CTE SQL generated by `EventSignature` matches seeded rows.
const TRANSFER_TOPIC0: [u8; 32] = [
    0xdd, 0xf2, 0x52, 0xad, 0x1b, 0xe2, 0xc8, 0x9b, 0x69, 0xc2, 0xb0, 0x68, 0xfc, 0x37, 0x8d, 0xaa,
    0x95, 0x2b, 0xa7, 0xf1, 0x63, 0xc4, 0xa1, 0x16, 0x28, 0xf5, 0x5a, 0x4d, 0xf5, 0x23, 0xb3, 0xef,
];

/// Event signature hash: 40% Transfer, else one of ~200 pseudo-events,
/// skewed. Stored in both `selector` and `topic0` (production convention:
/// selector = topics[0]).
fn sig_hash(rng: &mut StdRng) -> Vec<u8> {
    if rng.random::<f64>() < 0.4 {
        return TRANSFER_TOPIC0.to_vec();
    }
    let r: f64 = rng.random();
    let idx = ((r * r) * 200.0) as u64;
    let mut b = vec![0u8; 32];
    b[0] = 0xEE;
    b[8..16].copy_from_slice(&idx.to_be_bytes());
    b
}

struct BlockBatch {
    blocks: Vec<BlockRow>,
    txs: Vec<TxRow>,
    logs: Vec<LogRow>,
    receipts: Vec<ReceiptRow>,
}

/// Generate blocks [from, to) deterministically (same rng stream state
/// regardless of batching, because everything derives from one rng that
/// the caller threads through).
fn generate(rng: &mut StdRng, shape: &Shape, from: i64, to: i64) -> BlockBatch {
    let n = (to - from) as usize;
    let mut out = BlockBatch {
        blocks: Vec::with_capacity(n),
        txs: Vec::with_capacity(n * shape.txs_per_block as usize),
        logs: Vec::with_capacity(n * shape.logs_per_block as usize),
        receipts: Vec::with_capacity(n * shape.txs_per_block as usize),
    };

    for num in from..to {
        let block_hash = bytes::<32>(rng);
        out.blocks.push(BlockRow {
            num,
            hash: block_hash,
            parent_hash: bytes::<32>(rng),
            timestamp: ts(num),
            timestamp_ms: ts(num).timestamp_millis(),
            gas_limit: 3_000_000_000,
            gas_used: rng.random_range(100_000..30_000_000),
            miner: addr(rng, 9, 16),
            extra_data: None,
            consensus_proposer: None,
        });

        let mut tx_hashes = Vec::with_capacity(shape.txs_per_block as usize);
        for idx in 0..shape.txs_per_block as i32 {
            let hash = bytes::<32>(rng);
            tx_hashes.push(hash.clone());
            let from_addr = addr(rng, 3, 50_000);
            let mut input = vec![0u8; 4 + 64];
            rng.fill(&mut input[..]);
            out.txs.push(TxRow {
                block_num: num,
                block_timestamp: ts(num),
                idx,
                hash: hash.clone(),
                tx_type: 0,
                from: from_addr.clone(),
                to: Some(addr(rng, 4, 20_000)),
                value: if rng.random::<f64>() < 0.8 {
                    "0".to_string()
                } else {
                    format!("{}", rng.random_range(1u64..u64::MAX))
                },
                input,
                gas_limit: 200_000,
                max_fee_per_gas: format!("{}", rng.random_range(1u64..100)),
                max_priority_fee_per_gas: "1".to_string(),
                gas_used: Some(rng.random_range(21_000..200_000)),
                nonce_key: vec![0],
                nonce: num * 100 + idx as i64,
                call_count: 1,
                ..Default::default()
            });
            out.receipts.push(ReceiptRow {
                block_num: num,
                block_timestamp: ts(num),
                tx_idx: idx,
                tx_hash: hash,
                from: from_addr,
                to: Some(addr(rng, 4, 20_000)),
                contract_address: None,
                gas_used: 21_000,
                cumulative_gas_used: 21_000 * (idx as i64 + 1),
                effective_gas_price: Some("1".to_string()),
                status: Some(1),
                fee_payer: Some(addr(rng, 5, 1_000)),
                ..Default::default()
            });
        }

        for log_idx in 0..shape.logs_per_block as i32 {
            let tx_idx = log_idx % shape.txs_per_block as i32;
            let a = addr(rng, 6, 20_000);
            let t1 = topic_from_addr(&addr(rng, 3, 50_000));
            let sig = sig_hash(rng);
            let data = if sig == TRANSFER_TOPIC0 {
                // Transfer(value): 32-byte uint256, value in the tail.
                let mut d = vec![0u8; 32];
                d[24..32].copy_from_slice(&rng.random_range(1u64..u64::MAX).to_be_bytes());
                d
            } else {
                let mut d = vec![0u8; 96];
                rng.fill(&mut d[..]);
                d
            };
            out.logs.push(LogRow {
                block_num: num,
                block_timestamp: ts(num),
                log_idx,
                tx_idx,
                tx_hash: tx_hashes[tx_idx as usize].clone(),
                address: a,
                selector: Some(sig.clone()),
                topic0: Some(sig),
                topic1: Some(t1),
                topic2: Some(topic_from_addr(&addr(rng, 4, 20_000))),
                topic3: None,
                data,
                is_virtual_forward: false,
            });
        }
    }

    out
}

async fn connect(env: &str, default: &str) -> Pool {
    let base = std::env::var(env).unwrap_or_else(|_| default.to_string());
    let mut url = url::Url::parse(&base).expect("invalid database url");
    url.set_path(&format!("/{BENCH_DB}"));
    create_pool(url.as_str())
        .await
        .unwrap_or_else(|e| panic!("cannot connect to {env} ({url}): {e}"))
}

async fn reset(pool: &Pool) {
    let conn = pool.get().await.unwrap();
    conn.batch_execute("DROP TABLE IF EXISTS blocks, txs, logs, receipts, sync_state CASCADE")
        .await
        .unwrap();
    drop(conn);
    run_migrations(pool).await.unwrap();
}

async fn write_batch(pool: &Pool, b: &BlockBatch) {
    writer::write_blocks(pool, &b.blocks).await.unwrap();
    writer::write_txs(pool, &b.txs).await.unwrap();
    writer::write_logs(pool, &b.logs).await.unwrap();
    writer::write_receipts(pool, &b.receipts).await.unwrap();
}

async fn table_sizes(pool: &Pool, hypertable: bool) -> Vec<(String, i64)> {
    let conn = pool.get().await.unwrap();
    let mut out = Vec::new();
    for table in ["blocks", "txs", "logs", "receipts"] {
        let sql = if hypertable {
            format!("SELECT hypertable_size('{table}'::regclass)")
        } else {
            format!("SELECT pg_total_relation_size('{table}'::regclass)")
        };
        let size: i64 = conn.query_one(&sql, &[]).await.unwrap().get(0);
        out.push((table.to_string(), size));
    }
    out
}

fn mib(bytes: i64) -> f64 {
    bytes as f64 / 1024.0 / 1024.0
}

async fn count_txs(pool: &Pool) -> i64 {
    let conn = pool.get().await.unwrap();
    match conn.query_one("SELECT count(*) FROM txs", &[]).await {
        Ok(row) => row.get(0),
        Err(_) => -1,
    }
}

/// Collect sample keys for lookups from a bounded region via one scan.
async fn sample_keys(pool: &Pool, lo: i64, hi: i64, n: i64) -> Vec<(Vec<u8>, i64)> {
    let conn = pool.get().await.unwrap();
    conn.query(
        "SELECT hash, block_num FROM txs
         WHERE block_num >= $1 AND block_num < $2 AND idx = 0
           AND block_num % ((($2 - $1) / $3)::int8) = 0
         ORDER BY block_num",
        &[&lo, &hi, &n],
    )
    .await
    .unwrap()
    .into_iter()
    .map(|r| (r.get(0), r.get(1)))
    .collect()
}

struct BenchResult {
    p50_ms: f64,
    p95_ms: f64,
    rows: u64,
}

/// Run `iters` timed executions (after 2 warmups), cycling through params.
async fn bench(
    pool: &Pool,
    sql: &str,
    params: &[Vec<Box<dyn ToSql + Sync + Send>>],
    iters: usize,
) -> BenchResult {
    let conn = pool.get().await.unwrap();
    let mut times = Vec::with_capacity(iters);
    let mut rows = 0u64;
    for i in 0..iters + 2 {
        let p = &params[i % params.len()];
        let refs: Vec<&(dyn ToSql + Sync)> = p
            .iter()
            .map(|b| b.as_ref() as &(dyn ToSql + Sync))
            .collect();
        let start = Instant::now();
        let out = conn.query(sql, &refs).await.unwrap();
        let elapsed = start.elapsed().as_secs_f64() * 1000.0;
        if i >= 2 {
            times.push(elapsed);
            rows += out.len() as u64;
        }
    }
    times.sort_by(|a, b| a.partial_cmp(b).unwrap());
    BenchResult {
        p50_ms: times[times.len() / 2],
        p95_ms: times[((times.len() as f64 * 0.95) as usize).min(times.len() - 1)],
        rows,
    }
}

fn one<T: ToSql + Sync + Send + 'static>(v: T) -> Vec<Box<dyn ToSql + Sync + Send>> {
    vec![Box::new(v)]
}

/// Like [`bench`], but cycling literal SQL statements (no bind params) —
/// needed for event-CTE pushdown, which rewrites literals in the SQL text.
async fn bench_sqls(pool: &Pool, sqls: &[String], iters: usize) -> BenchResult {
    let conn = pool.get().await.unwrap();
    let mut times = Vec::with_capacity(iters);
    let mut rows = 0u64;
    for i in 0..iters + 2 {
        let sql = &sqls[i % sqls.len()];
        let start = Instant::now();
        let out = conn.query(sql.as_str(), &[]).await.unwrap();
        let elapsed = start.elapsed().as_secs_f64() * 1000.0;
        if i >= 2 {
            times.push(elapsed);
            rows += out.len() as u64;
        }
    }
    times.sort_by(|a, b| a.partial_cmp(b).unwrap());
    BenchResult {
        p50_ms: times[times.len() / 2],
        p95_ms: times[((times.len() as f64 * 0.95) as usize).min(times.len() - 1)],
        rows,
    }
}

#[tokio::test]
#[ignore = "Only run explicitly with --ignored"]
async fn bench_timescale_vs_stock() {
    let shape = Shape::from_env();
    println!(
        "\n=== seeding {} blocks x ({} txs, {} logs, {} receipts) — chunk_blocks {} ===",
        shape.blocks,
        shape.txs_per_block,
        shape.logs_per_block,
        shape.txs_per_block,
        shape.chunk_blocks
    );

    let stock = connect(
        "STOCK_DATABASE_URL",
        "postgresql://tidx:tidx@localhost:5433/tidx",
    )
    .await;
    let tsdb = connect(
        "TIMESCALE_DATABASE_URL",
        "postgresql://tidx:tidx@localhost:5434/tidx",
    )
    .await;

    let ts_cfg = TimescaleConfig {
        enabled: true,
        chunk_blocks: shape.chunk_blocks as u64,
        hot_window_blocks: shape.chunk_blocks as u64,
        interval_secs: 60,
    };

    // BENCH_REUSE=1 skips seeding/compression when both DBs already hold
    // exactly this dataset (fast iteration on the query set).
    let expected_txs = shape.blocks * shape.txs_per_block;
    let reuse = std::env::var("BENCH_REUSE").is_ok_and(|v| v == "1")
        && count_txs(&stock).await == expected_txs
        && count_txs(&tsdb).await == expected_txs;

    if reuse {
        println!("reusing existing seeded dataset");
    } else {
        reset(&stock).await;
        reset(&tsdb).await;
        assert!(timescale::setup(&tsdb, &ts_cfg).await.unwrap());

        // ── Seed identical data into both through the production write path ──
        let mut rng = StdRng::seed_from_u64(SEED);
        let batch_blocks = 5_000;
        let seed_start = Instant::now();
        let mut written = 0i64;
        while written < shape.blocks {
            let to = (written + batch_blocks).min(shape.blocks);
            let batch = generate(&mut rng, &shape, written, to);
            tokio::join!(write_batch(&stock, &batch), write_batch(&tsdb, &batch));
            written = to;
            if written % 25_000 == 0 {
                println!(
                    "  seeded {written}/{} blocks ({:.0}s)",
                    shape.blocks,
                    seed_start.elapsed().as_secs_f64()
                );
            }
        }
        println!("seeding done in {:.0}s", seed_start.elapsed().as_secs_f64());
    }

    writer::save_sync_state(
        &stock,
        &SyncState {
            chain_id: CHAIN_ID,
            head_num: shape.blocks as u64,
            synced_num: shape.blocks as u64,
            tip_num: shape.blocks as u64,
            backfill_num: Some(0),
            sync_rate: None,
            started_at: None,
        },
    )
    .await
    .unwrap();
    writer::save_sync_state(
        &tsdb,
        &SyncState {
            chain_id: CHAIN_ID,
            head_num: shape.blocks as u64,
            synced_num: shape.blocks as u64,
            tip_num: shape.blocks as u64,
            backfill_num: Some(0),
            sync_rate: None,
            started_at: None,
        },
    )
    .await
    .unwrap();

    let before = table_sizes(&tsdb, true).await;

    // ── Compress cold chunks on the Timescale side ──
    let compress_start = Instant::now();
    let converted = timescale::run_pass(&tsdb, CHAIN_ID, &ts_cfg).await.unwrap();
    println!(
        "\ncompressed {} chunks in {:.0}s",
        converted.len(),
        compress_start.elapsed().as_secs_f64()
    );

    for pool in [&stock, &tsdb] {
        let conn = pool.get().await.unwrap();
        conn.batch_execute("VACUUM ANALYZE blocks, txs, logs, receipts")
            .await
            .unwrap();
    }

    // ── Sizes ──
    let stock_sizes = table_sizes(&stock, false).await;
    let after = table_sizes(&tsdb, true).await;
    println!("\n=== disk (MiB): stock vs timescale (pre-compress → post) ===");
    let (mut ts_total, mut stock_total) = (0i64, 0i64);
    for i in 0..4 {
        println!(
            "  {:<9} stock {:>9.1}   ts {:>9.1} → {:>8.1}",
            stock_sizes[i].0,
            mib(stock_sizes[i].1),
            mib(before[i].1),
            mib(after[i].1),
        );
        stock_total += stock_sizes[i].1;
        ts_total += after[i].1;
    }
    println!(
        "  {:<9} stock {:>9.1}   ts            → {:>8.1}   ({:.1}x smaller)",
        "TOTAL",
        mib(stock_total),
        mib(ts_total),
        stock_total as f64 / ts_total as f64
    );

    // ── Sample keys ──
    let cold_hi = shape.hot_floor();
    let cold_keys = sample_keys(&stock, 0, cold_hi, 40).await;
    let hot_keys = sample_keys(&stock, cold_hi, shape.blocks, 40).await;
    assert!(cold_keys.len() >= 10 && hot_keys.len() >= 10);

    let conn = stock.get().await.unwrap();
    let cold_addrs: Vec<Vec<u8>> = conn
        .query(
            "SELECT DISTINCT address FROM logs WHERE block_num BETWEEN 1000 AND 1200 LIMIT 20",
            &[],
        )
        .await
        .unwrap()
        .into_iter()
        .map(|r| r.get(0))
        .collect();
    let common_selector: Vec<u8> = conn
        .query_one(
            "SELECT selector FROM logs WHERE block_num < 1000 GROUP BY selector ORDER BY count(*) DESC LIMIT 1",
            &[],
        )
        .await
        .unwrap()
        .get(0);
    let rare_selector: Vec<u8> = conn
        .query_one(
            "SELECT selector FROM logs WHERE block_num < 50000 GROUP BY selector ORDER BY count(*) ASC LIMIT 1",
            &[],
        )
        .await
        .unwrap()
        .get(0);
    // Cold tx sender addresses (bytea) for join shapes.
    let from_addrs: Vec<Vec<u8>> = conn
        .query(
            "SELECT DISTINCT \"from\" FROM txs WHERE block_num BETWEEN 1000 AND 1100 LIMIT 10",
            &[],
        )
        .await
        .unwrap()
        .into_iter()
        .map(|r| r.get(0))
        .collect();
    // Transfer sender topics (bytea) for the decoded-event filter shape.
    let transfer_topic1s: Vec<Vec<u8>> = conn
        .query(
            "SELECT DISTINCT topic1 FROM logs \
             WHERE selector = $1 AND block_num BETWEEN 1000 AND 1100 LIMIT 5",
            &[&TRANSFER_TOPIC0.to_vec()],
        )
        .await
        .unwrap()
        .into_iter()
        .map(|r| r.get(0))
        .collect();
    assert!(!transfer_topic1s.is_empty());
    drop(conn);

    // Production decoded-event SQL: `apply_event_signature_ctes_postgres`
    // is the same entry point the /query endpoint uses.
    //
    // Note: the decoded-column pushdown rewrite (`"from" = '0x…'` →
    // `topic1 = '0x…'`) emits ClickHouse-style hex-string literals, which
    // PG silently mis-parses against BYTEA topics (escape format ⇒ zero
    // rows) — a latent main bug. We therefore filter on `topic1` directly
    // with a bytea param: exactly what a corrected pushdown would run.
    const TRANSFER_SIG: &str = "Transfer(address indexed from, address indexed to, uint256 value)";
    let cte = |outer: &str| -> String {
        apply_event_signature_ctes_postgres(outer, &[TRANSFER_SIG]).expect("cte generation")
    };

    // ── Queries ──
    let mid = cold_hi / 2;
    let window = shape.chunk_blocks;
    struct Q {
        name: &'static str,
        sql: String,
        params: Vec<Vec<Box<dyn ToSql + Sync + Send>>>,
    }
    let queries = vec![
        Q {
            name: "tx_by_hash cold UNBOUNDED",
            sql: "SELECT * FROM txs WHERE hash = $1".into(),
            params: cold_keys.iter().map(|(h, _)| one(h.clone())).collect(),
        },
        Q {
            name: "tx_by_hash cold bounded",
            sql: "SELECT * FROM txs WHERE hash = $1 AND block_num BETWEEN $2 AND $3".into(),
            params: cold_keys
                .iter()
                .map(|(h, b)| {
                    vec![
                        Box::new(h.clone()) as Box<dyn ToSql + Sync + Send>,
                        Box::new(b - 100),
                        Box::new(b + 100),
                    ]
                })
                .collect(),
        },
        Q {
            name: "tx_by_hash hot UNBOUNDED",
            sql: "SELECT * FROM txs WHERE hash = $1".into(),
            params: hot_keys.iter().map(|(h, _)| one(h.clone())).collect(),
        },
        Q {
            // The serving pattern: probe the hot window first (chunk
            // exclusion → B-tree), fall back to unbounded on miss.
            name: "tx_by_hash hot-first probe",
            sql: format!("SELECT * FROM txs WHERE hash = $1 AND block_num >= {cold_hi}"),
            params: hot_keys.iter().map(|(h, _)| one(h.clone())).collect(),
        },
        Q {
            name: "logs_by_txhash cold UNBOUNDED",
            sql: "SELECT * FROM logs WHERE tx_hash = $1".into(),
            params: cold_keys.iter().map(|(h, _)| one(h.clone())).collect(),
        },
        Q {
            name: "logs_by_addr cold bounded",
            sql: format!(
                "SELECT * FROM logs WHERE address = $1 AND block_num BETWEEN {mid} AND {} \
                 ORDER BY block_num DESC, log_idx DESC LIMIT 100",
                mid + window
            ),
            params: cold_addrs.iter().map(|a| one(a.clone())).collect(),
        },
        Q {
            // Row-value comparison defeats vectorization + batch metadata
            // pruning on the columnstore: kept as a measured anti-pattern.
            name: "logs keyset cold (row-cmp) ⚠",
            sql: "SELECT * FROM logs WHERE (block_num, log_idx) < ($1, $2) \
                  ORDER BY block_num DESC, log_idx DESC LIMIT 25"
                .into(),
            params: (0..20)
                .map(|i| {
                    vec![
                        Box::new(mid - i * 1000) as Box<dyn ToSql + Sync + Send>,
                        Box::new(5i32),
                    ]
                })
                .collect(),
        },
        Q {
            // Hybrid keyset: the redundant range bound gives the
            // columnstore its batch-metadata pushdown, the row comparison
            // gives stock B-trees their index condition. Fast on both —
            // the form consumers should use.
            name: "logs keyset cold (hybrid)",
            sql: "SELECT * FROM logs WHERE block_num <= $1 \
                  AND (block_num, log_idx) < ($1, $2) \
                  ORDER BY block_num DESC, log_idx DESC LIMIT 25"
                .into(),
            params: (0..20)
                .map(|i| {
                    vec![
                        Box::new(mid - i * 1000) as Box<dyn ToSql + Sync + Send>,
                        Box::new(5i32),
                    ]
                })
                .collect(),
        },
        Q {
            name: "txs⋈receipts cold 5k blocks",
            sql: format!(
                "SELECT count(*) FROM txs t JOIN receipts r \
                 ON r.block_num = t.block_num AND r.tx_idx = t.idx \
                 WHERE t.block_num BETWEEN {mid} AND {}",
                mid + 5_000
            ),
            params: vec![vec![]],
        },
        Q {
            name: "agg count+sum cold 100k blk",
            sql: format!(
                "SELECT count(*), sum(gas_used) FROM txs WHERE block_num BETWEEN 0 AND {}",
                100_000.min(cold_hi)
            ),
            params: vec![vec![]],
        },
        Q {
            name: "event shape: common selector",
            sql: format!(
                "SELECT count(*) FROM logs WHERE selector = $1 AND block_num BETWEEN {mid} AND {}",
                mid + window
            ),
            params: vec![one(common_selector.clone())],
        },
        Q {
            name: "event shape: rare selector",
            sql: format!(
                "SELECT count(*) FROM logs WHERE selector = $1 AND block_num BETWEEN {mid} AND {}",
                mid + window
            ),
            params: vec![one(rare_selector.clone())],
        },
        Q {
            name: "join: tx detail by hash bnd",
            sql: "SELECT t.hash, t.\"from\", t.value, r.status, r.gas_used \
                  FROM txs t JOIN receipts r \
                  ON r.block_num = t.block_num AND r.tx_idx = t.idx \
                  WHERE t.hash = $1 AND t.block_num BETWEEN $2 AND $3"
                .into(),
            params: cold_keys
                .iter()
                .map(|(h, b)| {
                    vec![
                        Box::new(h.clone()) as Box<dyn ToSql + Sync + Send>,
                        Box::new(b - 100),
                        Box::new(b + 100),
                    ]
                })
                .collect(),
        },
        Q {
            name: "join: block page txs⋈receipts",
            sql: "SELECT t.idx, t.hash, r.status, r.gas_used \
                  FROM txs t JOIN receipts r \
                  ON r.block_num = t.block_num AND r.tx_idx = t.idx \
                  WHERE t.block_num = $1 ORDER BY t.idx"
                .into(),
            params: (0..20).map(|i| one(mid + i * 777)).collect(),
        },
        Q {
            name: "join: addr activity LIMIT 50",
            sql: format!(
                "SELECT t.hash, t.block_num, t.idx, r.status \
                 FROM txs t JOIN receipts r \
                 ON r.block_num = t.block_num AND r.tx_idx = t.idx \
                 WHERE t.\"from\" = $1 AND t.block_num BETWEEN {mid} AND {} \
                 ORDER BY t.block_num DESC, t.idx DESC LIMIT 50",
                mid + window
            ),
            params: from_addrs.iter().map(|a| one(a.clone())).collect(),
        },
        Q {
            name: "join: 3-way logs⋈txs⋈receipts",
            sql: format!(
                "SELECT l.block_num, l.log_idx, t.\"from\", r.fee_payer \
                 FROM logs l \
                 JOIN txs t ON t.block_num = l.block_num AND t.idx = l.tx_idx \
                 JOIN receipts r ON r.block_num = l.block_num AND r.tx_idx = l.tx_idx \
                 WHERE l.address = $1 AND l.block_num BETWEEN {mid} AND {} \
                 ORDER BY l.block_num DESC, l.log_idx DESC LIMIT 100",
                mid + window
            ),
            params: cold_addrs.iter().map(|a| one(a.clone())).collect(),
        },
        Q {
            name: "cte: Transfer by from topic1",
            sql: cte(&format!(
                "SELECT block_num, log_idx, \"to\", \"value\" FROM Transfer \
                 WHERE topic1 = $1 AND block_num BETWEEN {mid} AND {} \
                 ORDER BY block_num DESC LIMIT 50",
                mid + window
            )),
            params: transfer_topic1s.iter().map(|t| one(t.clone())).collect(),
        },
    ];

    println!("\n=== query latency, ms (25 iters, p50/p95) ===");
    println!(
        "  {:<30} {:>8} {:>8}   {:>8} {:>8}   {:>6}",
        "query", "stock", "p95", "tsdb", "p95", "ratio"
    );
    for q in &queries {
        let iters = 25;
        let s = bench(&stock, &q.sql, &q.params, iters).await;
        let t = bench(&tsdb, &q.sql, &q.params, iters).await;
        println!(
            "  {:<30} {:>8.2} {:>8.2}   {:>8.2} {:>8.2}   {:>5.1}x   (rows {} / {})",
            q.name,
            s.p50_ms,
            s.p95_ms,
            t.p50_ms,
            t.p95_ms,
            t.p50_ms / s.p50_ms,
            s.rows,
            t.rows,
        );
        assert_eq!(s.rows, t.rows, "row mismatch on {}", q.name);
    }

    // ── tempo-api2 production shapes ──
    // Mirrors the SQL tempo-api2 (src/apps/data/*.ts) sends to tidx's
    // /query endpoint: literals inlined (incl. '0x…' hex, converted below
    // exactly like `execute_query_postgres` does), hybrid keyset from
    // Cursor.keyset, UNION-per-side address scoping, capped counts.
    let hex = |b: &[u8]| b.iter().map(|x| format!("{x:02x}")).collect::<String>();
    let conn = stock.get().await.unwrap();
    let to_addr_hex: String = conn
        .query_one(
            "SELECT encode(\"to\", 'hex') FROM txs WHERE block_num BETWEEN 1000 AND 1010 AND \"to\" IS NOT NULL LIMIT 1",
            &[],
        )
        .await
        .unwrap()
        .get(0);
    let hydrate_keys = sample_keys(&stock, mid, mid + 2_000, 20).await;
    // Stand-in FeeManager: the hottest log-emitting contract (fee-amm routes
    // filter one contract address + two event selectors over full history).
    let fee_mgr_hex: String = conn
        .query_one(
            "SELECT encode(address, 'hex') FROM logs WHERE block_num < 5000 \
             GROUP BY address ORDER BY count(*) DESC LIMIT 1",
            &[],
        )
        .await
        .unwrap()
        .get(0);
    let mint_sel_hex: String = conn
        .query_one(
            "SELECT encode(selector, 'hex') FROM logs WHERE block_num < 5000 AND selector <> $1 \
             GROUP BY selector ORDER BY count(*) DESC LIMIT 1",
            &[&TRANSFER_TOPIC0.to_vec()],
        )
        .await
        .unwrap()
        .get(0);
    let legacy_sel_hex: String = hex(&TRANSFER_TOPIC0);
    let order_topic1_hexes: Vec<String> = conn
        .query(
            "SELECT DISTINCT encode(topic1, 'hex') FROM logs \
             WHERE address = decode($1, 'hex') AND block_num BETWEEN $2 AND $3 LIMIT 20",
            &[&fee_mgr_hex, &mid, &(mid + 2_000)],
        )
        .await
        .unwrap()
        .into_iter()
        .map(|r| r.get(0))
        .collect();
    drop(conn);
    assert!(hydrate_keys.len() >= 10);
    assert!(order_topic1_hexes.len() >= 5);

    let tx_cols = "block_num, block_timestamp, idx, hash, type, \"from\", \"to\", value, input, \
                   gas_limit, max_fee_per_gas, max_priority_fee_per_gas, \
                   nonce_key, nonce, fee_token, fee_payer, valid_before, valid_after";
    let receipt_cols = "block_num, block_timestamp, tx_idx, tx_hash, \"from\", \"to\", \
                        contract_address, gas_used, cumulative_gas_used, effective_gas_price, \
                        status, fee_payer";
    let addr_union_page = |addr_hex: &str| -> String {
        let keyset = format!("(block_num <= {mid} AND (block_num, idx) < ({mid}, 4))");
        let side = |side: &str| {
            format!(
                "(SELECT {tx_cols} FROM txs WHERE \"{side}\" = '0x{addr_hex}' AND {keyset} \
                 ORDER BY block_num DESC, idx DESC LIMIT 21)"
            )
        };
        format!(
            "{} UNION {} ORDER BY block_num DESC, idx DESC LIMIT 21",
            side("from"),
            side("to")
        )
    };
    let hydrate_blocks = hydrate_keys
        .iter()
        .map(|(_, b)| b.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    let hydrate_hashes = hydrate_keys
        .iter()
        .map(|(h, _)| format!("'0x{}'", hex(h)))
        .collect::<Vec<_>>()
        .join(", ");
    let (hyd_lo, hyd_hi) = (
        hydrate_keys.iter().map(|(_, b)| *b).min().unwrap(),
        hydrate_keys.iter().map(|(_, b)| *b).max().unwrap(),
    );

    // ── Event CTEs + tempo-api2 literal-SQL shapes ──
    let cte_queries: Vec<(&str, Vec<String>)> = vec![
        (
            "api /transactions?address=",
            from_addrs
                .iter()
                .take(5)
                .map(|a| addr_union_page(&hex(a)))
                .collect(),
        ),
        (
            "api /transactions count",
            from_addrs
                .iter()
                .take(5)
                .map(|a| {
                    let h = hex(a);
                    format!(
                        "SELECT count(*) AS total FROM (\
                         (SELECT block_num, idx FROM txs WHERE \"from\" = '0x{h}' LIMIT 10000) \
                         UNION \
                         (SELECT block_num, idx FROM txs WHERE \"to\" = '0x{h}' LIMIT 10000)\
                         ) AS capped"
                    )
                })
                .collect(),
        ),
        (
            "api /blocks page",
            (0..10)
                .map(|i| {
                    format!(
                        "SELECT hash, num, timestamp FROM blocks WHERE ((num) < ({})) \
                         ORDER BY num DESC LIMIT 26",
                        mid - i * 1000
                    )
                })
                .collect(),
        ),
        (
            "api /blocks/:b?closest=ts",
            vec![format!(
                "SELECT num, timestamp FROM blocks \
                 WHERE timestamp <= '{}' AND timestamp >= '{}' \
                 ORDER BY timestamp DESC, num DESC LIMIT 1",
                ts(mid).to_rfc3339(),
                ts(mid - 300).to_rfc3339()
            )],
        ),
        (
            "api /txs/receipts?to=addr",
            vec![format!(
                "SELECT {receipt_cols} FROM receipts WHERE tx_hash IN \
                 (SELECT hash FROM txs WHERE \"to\" = '0x{to_addr_hex}') \
                 ORDER BY block_num DESC, tx_idx DESC LIMIT 21"
            )],
        ),
        (
            "api tx hydrate (webhooks)",
            vec![format!(
                "SELECT {tx_cols} FROM txs WHERE block_num IN ({hydrate_blocks}) \
                 AND hash IN ({hydrate_hashes})"
            )],
        ),
        (
            "api receipts logs hydrate",
            vec![format!(
                "SELECT tx_hash, block_num, tx_idx, log_idx, address, selector, topic1, \
                 topic2, topic3, data, block_timestamp FROM logs \
                 WHERE block_num BETWEEN {hyd_lo} AND {hyd_hi} \
                 AND tx_hash IN ({hydrate_hashes}) ORDER BY block_num ASC, log_idx ASC"
            )],
        ),
        (
            // GET /v1/fee-amm/pools — whole-history GROUP BY over raw logs
            // (production sends this to ClickHouse; benched here to answer
            // whether the columnstore could serve it). PG dialect deltas:
            // count(*) for count(), subquery alias.
            "api /fee-amm/pools GROUPBY",
            vec![format!(
                "SELECT topic2, topic3, mint_count, first_at, last_at FROM (\
                 SELECT topic2, topic3, count(*) AS mint_count, \
                        min(block_timestamp) AS first_at, max(block_timestamp) AS last_at \
                 FROM logs \
                 WHERE address = '0x{fee_mgr_hex}' \
                   AND selector IN ('0x{mint_sel_hex}', '0x{legacy_sel_hex}') \
                 GROUP BY topic2, topic3\
                 ) AS pools \
                 ORDER BY mint_count DESC, topic2 DESC, topic3 DESC LIMIT 26"
            )],
        ),
        (
            // GET /v1/fee-amm/mints — newest-first event feed for one contract.
            "api /fee-amm/mints page",
            vec![format!(
                "SELECT tx_hash, block_num, log_idx, block_timestamp AS block_time, \
                 selector, topic1, topic2, topic3, data FROM logs \
                 WHERE address = '0x{fee_mgr_hex}' \
                   AND selector IN ('0x{mint_sel_hex}', '0x{legacy_sel_hex}') \
                 ORDER BY block_num DESC, log_idx DESC LIMIT 26"
            )],
        ),
        (
            // GET /v1/fee-amm/mints — whole-history count (15 s api cache).
            "api /fee-amm/mints count",
            vec![format!(
                "SELECT count(*) AS total FROM logs \
                 WHERE address = '0x{fee_mgr_hex}' \
                   AND selector IN ('0x{mint_sel_hex}', '0x{legacy_sel_hex}')"
            )],
        ),
        (
            // GET /v1/exchange/orders/:id/fills → resolveOrderStates: latest
            // event per order below the page + all in-page events. Production
            // uses ClickHouse argMax; benched as the PG DISTINCT ON idiom.
            "api /exchange orderstates†",
            vec![{
                let topics = order_topic1_hexes
                    .iter()
                    .map(|t| format!("'0x{t}'"))
                    .collect::<Vec<_>>()
                    .join(", ");
                let filter = format!(
                    "address = '0x{fee_mgr_hex}' \
                     AND selector IN ('0x{mint_sel_hex}', '0x{legacy_sel_hex}') \
                     AND topic1 IN ({topics})"
                );
                format!(
                    "SELECT * FROM (\
                     SELECT DISTINCT ON (topic1) topic1, topic3 AS t3, data AS payload, \
                            -1::int8 AS bn, -1::int4 AS li \
                     FROM logs WHERE {filter} AND block_num < {mid} \
                     ORDER BY topic1, block_num DESC, log_idx DESC\
                     ) AS baseline \
                     UNION ALL \
                     SELECT topic1, topic3 AS t3, data AS payload, block_num AS bn, log_idx AS li \
                     FROM logs WHERE {filter} AND block_num BETWEEN {mid} AND {}",
                    mid + 2_000
                )
            }],
        ),
        (
            "cte: Transfer count window",
            vec![cte(&format!(
                "SELECT count(*) FROM Transfer WHERE block_num BETWEEN {mid} AND {}",
                mid + window
            ))],
        ),
        (
            // Aggregate args aren't seen by used-column extraction, so
            // reference the decoded column in a subquery select list.
            "cte: Transfer sum(value) win",
            vec![cte(&format!(
                "SELECT count(*), sum(t.v) FROM \
                 (SELECT \"value\" AS v FROM Transfer WHERE block_num BETWEEN {mid} AND {}) t",
                mid + window
            ))],
        ),
    ];

    for (name, sqls) in &cte_queries {
        // Same literal conversion the production /query pipeline applies.
        let sqls: Vec<String> = sqls
            .iter()
            .map(|s| tidx::query::convert_hex_literals_postgres(s))
            .collect();
        let iters = 25;
        let s = bench_sqls(&stock, &sqls, iters).await;
        let t = bench_sqls(&tsdb, &sqls, iters).await;
        println!(
            "  {:<30} {:>8.2} {:>8.2}   {:>8.2} {:>8.2}   {:>5.1}x   (rows {} / {})",
            name,
            s.p50_ms,
            s.p95_ms,
            t.p50_ms,
            t.p95_ms,
            t.p50_ms / s.p50_ms,
            s.rows,
            t.rows,
        );
        assert_eq!(s.rows, t.rows, "row mismatch on {name}");
    }

    // ── Show pruning evidence for the headline shape ──
    let conn = tsdb.get().await.unwrap();
    let (h, _) = &cold_keys[0];
    let plan = conn
        .query(
            "EXPLAIN (ANALYZE, COSTS OFF, TIMING OFF, SUMMARY ON) SELECT * FROM txs WHERE hash = $1",
            &[h],
        )
        .await
        .unwrap();
    println!("\n=== EXPLAIN: unbounded tx_by_hash on timescale ===");
    for row in plan.iter().take(12) {
        println!("  {}", row.get::<_, String>(0));
    }
}
