use std::path::PathBuf;

use anyhow::{bail, Result};
use clap::Args as ClapArgs;
use dialoguer::{Confirm, Input, Select};

#[derive(ClapArgs)]
pub struct Args {
    /// Output path for config file
    #[arg(short, long, default_value = "config.toml")]
    pub output: PathBuf,

    /// Overwrite existing config file
    #[arg(long)]
    pub force: bool,
}

const TEMPO_NETWORKS: &[(&str, u64, &str)] = &[
    ("Presto (mainnet)", 4217, "https://rpc.tempo.xyz"),
    ("Andantino (testnet)", 42429, "https://rpc.testnet.tempo.xyz"),
    ("Moderato", 42431, "https://rpc.moderato.tempo.xyz"),
    ("Custom", 0, ""),
];

pub fn run(args: Args) -> Result<()> {
    if args.output.exists() && !args.force {
        bail!(
            "Config file already exists: {}. Use --force to overwrite.",
            args.output.display()
        );
    }

    println!("\n🔫 tidx init\n");

    let network_idx = Select::new()
        .with_prompt("Select network")
        .items(&TEMPO_NETWORKS.iter().map(|(name, _, _)| *name).collect::<Vec<_>>())
        .default(0)
        .interact()?;

    let (name, chain_id, rpc_url) = if network_idx == TEMPO_NETWORKS.len() - 1 {
        let name: String = Input::new()
            .with_prompt("Chain name")
            .interact_text()?;

        let chain_id: u64 = Input::new()
            .with_prompt("Chain ID")
            .interact_text()?;

        let rpc_url: String = Input::new()
            .with_prompt("RPC URL")
            .interact_text()?;

        (name, chain_id, rpc_url)
    } else {
        let (name, chain_id, rpc_url) = TEMPO_NETWORKS[network_idx];
        (name.to_string(), chain_id, rpc_url.to_string())
    };

    let pg_url: String = Input::new()
        .with_prompt("PostgreSQL URL")
        .default("postgres://localhost:5432/tidx".to_string())
        .interact_text()?;

    let enable_duckdb = Confirm::new()
        .with_prompt("Enable DuckDB for analytics?")
        .default(true)
        .interact()?;

    let duckdb_path = if enable_duckdb {
        let path: String = Input::new()
            .with_prompt("DuckDB file path")
            .default(format!("{}.duckdb", name.to_lowercase().replace(' ', "_").replace(['(', ')'], "")))
            .interact_text()?;
        Some(path)
    } else {
        None
    };

    let http_port: u16 = Input::new()
        .with_prompt("HTTP API port")
        .default(8080)
        .interact_text()?;

    let config = generate_config(&name, chain_id, &rpc_url, &pg_url, duckdb_path.as_deref(), http_port);

    std::fs::write(&args.output, &config)?;

    println!("\n✅ Config written to {}", args.output.display());
    println!("\nNext steps:");
    println!("  1. Start PostgreSQL");
    println!("  2. Run: tidx up");
    println!("  3. Query: curl \"http://localhost:{http_port}/query?chainId={chain_id}&sql=SELECT * FROM blocks LIMIT 5\"");

    Ok(())
}

fn generate_config(
    name: &str,
    chain_id: u64,
    rpc_url: &str,
    pg_url: &str,
    duckdb_path: Option<&str>,
    http_port: u16,
) -> String {
    let mut config = format!(
        r#"# tidx configuration
# Generated by `tidx init`

[http]
enabled = true
port = {http_port}
bind = "0.0.0.0"

[http.rate_limit]
enabled = true
requests_per_window = 100
window_secs = 60

[prometheus]
enabled = true
port = 9090

[[chains]]
name = "{name}"
chain_id = {chain_id}
rpc_url = "{rpc_url}"
pg_url = "{pg_url}"
"#
    );

    if let Some(path) = duckdb_path {
        config.push_str(&format!("duckdb_path = \"{path}\"\n"));
    }

    config.push_str("backfill = true\n");
    config.push_str("batch_size = 100\n");

    config
}
