name: Auto Assign PR

on:
  pull_request:
    types: [opened, reopened]

permissions:
  id-token: write
  issues: write
  pull-requests: write

jobs:
  assign:
    uses: tempoxyz/gh-actions/.github/workflows/auto-assign-pr.yml@55fe3b63d9612623cc51e6c62d9d62fbcb175fb0 # 2026-09-29T01-25-15Z-55fe3b63
