name: Auto Assign PR

on:
  pull_request:
    types: [opened, reopened]

permissions:
  id-token: write
  issues: write
  pull-requests: write

jobs:
  assign:
    uses: tempoxyz/gh-actions/.github/workflows/auto-assign-pr.yml@5840979a7c849cbe541c67431ec7315cd6396e3b
