name: dependencies

on:
  schedule:
    - cron: "0 0 * * 1" # Monday midnight
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: tempoxyz/ci/.github/workflows/cargo-update-pr.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
